language: python
python:
  - "3.6"

cache: pip

# command to install dependencies
install: pip install -r requirements.text

# command to run tests
script:
  - nosetests --with-coverage --cover-package=app

after_success: coveralls