language: python
python:
  - "2.7"

cache: pip

# command to install dependencies
install: pip install -r requirements.txt

services:
  - postgresql

env:
  - SECRET="hOst@909@8928.?"
  - APP_SETTINGS="development"

before_script:
  - psql -c 'create database test_db;' -U postgres

# command to run tests
script:
  py.test --cov=app

after_success: coveralls
