language: python
python:
  - "2.7"

cache: pip

# command to install dependencies
install: pip install -r requirements.text

# command to run tests
script:
  - python setup.py install
  - nosetests --with-coverage --cover-package=app

after_success: coveralls