language: python
python:
  - "2.7"

cache: pip

# command to install dependencies
install: pip install -r requirements.txt

services:
  - postgresql

env:
  - DATABASE_URI=postgresql://localhost/bucketlist>

before_script:
  - psql -c 'create database test_db;' -U postgres

# command to run tests
script:
  #- nosetests --with-coverage --cover-package=app
  py.test --cov=app

after_success: coveralls
