language: python
python:
  - "2.7"

cache: pip

# command to install dependencies
install: pip install -r requirements.text

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

# command to run tests
script:
  - nosetests --with-coverage --cover-package=app

after_success: coveralls