"""empty message

Revision ID: 7c6ec7e2b925
Revises: 
Create Date: 2017-08-03 07:15:21.212361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6ec7e2b925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'buckets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buckets', type_='foreignkey')
    op.drop_column('buckets', 'user_id')
    # ### end Alembic commands ###
